language: objective-c
osx_image: xcode11
xcode_workspace: ConfigCI.xcworkspace
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 8
xcode_scheme: ConfigCI
cache:
  - bundler
  - cocoapods
before_install:
  - bundle install
  - bundle exec pod install --repo-update
install:
  - sudo systemsetup -settimezone Asia/Ho_Chi_Minh
before_script:
  - chmod a+x ./scripts/add-key.sh
  - ./scripts/add-key.sh
  - bundle exec danger
  